# encoding: UTF-8

control 'C-7.5' do
  title 'Ensure that swarm manager is run in auto-lock mode'
  desc  "
    You should review whether you wish to run Docker swarm manager in auto-lock mode.

    When Docker restarts, both the TLS key used to encrypt communication among swarm nodes, and the key used to encrypt and decrypt Raft logs on disk, are loaded into each manager node's memory. You could protect the mutual TLS encryption key and the key used to encrypt and decrypt Raft logs at rest. This protection could be enabled by initializing the swarm with the `--autolock` flag.

    With `--autolock `enabled, when Docker restarts, you must unlock the swarm first, using a key encryption key generated by Docker when the swarm was initialized.

    This has benefits in a high security environment, however these should be balanced against the support issues caused by the swarm not starting automatically if, for example the host were to experience an outage.
  "
  desc  'rationale', "
    You should review whether you wish to run Docker swarm manager in auto-lock mode.

    When Docker restarts, both the TLS key used to encrypt communication among swarm nodes, and the key used to encrypt and decrypt Raft logs on disk, are loaded into each manager node's memory. You could protect the mutual TLS encryption key and the key used to encrypt and decrypt Raft logs at rest. This protection could be enabled by initializing the swarm with the `--autolock` flag.

    With `--autolock `enabled, when Docker restarts, you must unlock the swarm first, using a key encryption key generated by Docker when the swarm was initialized.

    This has benefits in a high security environment, however these should be balanced against the support issues caused by the swarm not starting automatically if, for example the host were to experience an outage.
  "
  desc  'check', "
    You should run the command below
    ```
    docker info --format 'Swarm Autolock: {{ .Swarm.Cluster.Spec.EncryptionConfig.AutoLockManagers }}'
    ```
    If the result is `true`, auto-lock mode is enable.

    You could also run the command below. If a key value is returned, it means that the swarm was initialized with the `--autolock` flag. If the output is `no unlock key is set`, it means that swarm was NOT initialized with the `--autolock` flag.  This should be reviewed in line with the organization's IT Security policy.
    ```
    docker swarm unlock-key
    ```
  "
  desc  'fix', "
    If you are initializing a swarm, use the command below.
    ```
    docker swarm init --autolock
    ```
    If you want to set `--autolock` on an existing swarm manager node, use the following command.
    ```
    docker swarm update --autolock
    ```
  "
  impact 0.5
  tag severity:              'medium'
  tag severity_source:       'unassessed'
  tag nist:                  ['SC-28', 'AC-8 a']
  tag cci:                   ['CCI-001199', 'CCI-000051']
  tag cis_number:            '7.5'
  tag cis_rid:               '7.5'
  tag cis_benchmark:         'CIS Docker Benchmark v1.8.0'
  tag cis_rule_id:           'SV-0705r1_rule'
  tag cis_version:           '1.8.0'
  tag cis_level:             1
  tag cis_scored:            true
  if input('docker_target_mode') == 'container_only'
    tag implementation_status: 'not-applicable'
  else
    tag implementation_status: 'implemented'
  end
  tag exec_validated:          false

  if input('docker_target_mode') == 'container_only'
    describe "CIS Docker 7.5 — swarm manager auto-lock mode" do
      skip "not-applicable: AWS Fargate uses ECS scheduling; no Swarm manager auto-lock to enable."
    end
  else
    describe command('docker swarm unlock-key 2>&1') do
    its('stdout') { should include('SWMKEY-1') }
  end
  end
end
